name: CombinedSlots
main: jasonwynn10\CrossOnlineCount\Main
version: 0.2.0
api: [3.8.0]
load: STARTUP
author: "jasonwynn10"
description: "A PocketMine plugin which checks other servers for online players and displays THE INFORMATIONvia slappers"
